### ISSUE TITLE
Trino Error

### ISSUE THREAD

**Issue by CTJohnson** [zsvoboda/ngods-stocks#9]
First, awesome example.

Second, hopefully this is a silly issue which goes away easily.

Whenever I try to start the Trino container (e.g. docker-compose up)...it immediately shuts down with the following error:
'ERROR: Trino requires at least 4096 file descriptors (found 1024)'

Have you dealt with this before?

**Comment by CTJohnson** [comment]
Solution:

Increase the ulimits in the docker-compose for trino container:

```
ulimits:
  nproc: 65535
  nofile:
    soft: 20000
    hard: 40000
```
